# Generated by Django 5.0.7 on 2024-08-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_carts_remove_cart_item_cart_remove_cart_item_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_items',
            name='product',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
        migrations.DeleteModel(
            name='Cart_items',
        ),
    ]
