# Generated by Django 5.0.7 on 2024-07-24 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_delete_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.ImageField(default=0, upload_to='')),
                ('zipcode', models.ImageField(upload_to='')),
                ('state', models.CharField(choices=[('KERALA', 'KERALA'), ('TAMILNADU', 'TAMILNADU'), ('KARNATAK', 'KARNATAK'), ('ANDRAPREDEH', 'ANDRAPREDEH'), ('GUJARATH', 'GUJARATH'), ('RAJASTHA', 'RAJASTHA'), ('MAHARASTRA', 'MAHARASTRA'), ('MADHYAPRESHES', 'MADHYAPRESHES'), ('UP', 'UP'), ('BENGOL', 'BENGOL'), ('GOA', 'GOA'), ('ARUNACHAL', 'ARUNACHA'), ('ORISA', 'ORISA'), ('CHARGAND', 'CHARGAND'), ('SIKIM', 'SIKIM'), ('MEGALAYA', 'MEGALAYA'), ('JAMMU', 'JAMMU'), ('ORISA', 'ORISA'), ('HARIYANA', 'HARIYANA'), ('HIMACHA', 'HIMACHAL'), ('ASSAM', 'ASSAM'), ('CHANDIGAND', 'CHANDIGAND')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
