# Generated by Django 5.0.7 on 2024-08-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_cart_carts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
