# Generated by Django 5.0.7 on 2024-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_delete_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('CR', 'Crud'), ('MK', 'Milk'), ('LS', 'Lassi'), ('MS', 'MilkShake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IH', 'Ice-cream')], max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodapp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
